# Basic configs
model = "gfca"
dataset = "Elliptic"
device = "cuda:0"

encoding_size = 8
hidden_size = 32
num_layers = 2
dropout = 0.1
random_seed = 72

# Learning rate
lr = 0.001

# Drop Message rate
drop_rate = 0.25

metrics = ["AUC", "AP", "Recall"]

use_early_stopping = true
early_stopping_patience = 50

log_path = "./logs.txt"

# Dataset configs

[datasets.DGraph]
num_classes = 2
loss_weight = 50

[datasets.Cora]
num_classes = 7
loss_weight = 1

[datasets.Wikipedia]
num_classes = 2
loss_weight = 50

[datasets.Yelp]
num_classes = 2
loss_weight = 1

[datasets.Elliptic]
num_classes = 2
loss_weight = 50

[datasets.Ethereum]
num_classes = 2
loss_weight = 50

# Model configs

[models.gcn]
# GCN
weight_decay = 1e-5

[models.sage]
# GraphSAGE
weight_decay = 5e-7

[models.dropsage]
# GraphSAGE with CAFD
weight_decay = 5e-7

[models.dropgcn]
# GCN with CAFD
weight_decay = 1e-5

[models.mlpdropgcn]
# GCN with DropMessage, DropRate from MLP
weight_decay = 0e-4

[models.tgat]
# TGAT
weight_decay = 5e-7

[models.dagad]
# DAGAD
weight_decay = 5e-7

[models.h2gcn]
# H2GCN
weight_decay = 0e-4

[models.mlp]
# MLP
weight_decay = 0e-4

[models.amnet]
# AMNet
weight_decay = 1e-5

[models.gfca]
# GFCA
weight_decay = 1e-3
