# Basic configs
model = "mlpdropgcn"
dataset = "Cora"
device = "cpu"

hidden_size = 64
num_layers = 2
dropout = 0.0
random_seed = 0

# Learning rate
lr = 0.01

metrics = ["AUC", "AP"]

use_early_stopping = false
early_stopping_patience = 10

log_path = "./logs.txt"

# Dataset configs
[datasets.DGraph]
num_classes = 2

[datasets.Cora]
num_classes = 7

# Model configs
[models.gcn]
# GCN
weight_decay = 5e-7

[models.dropgcn]
# GCN with DropMessage
weight_decay = 0e-4
drop_rate = 0.25

[models.mlpdropgcn]
# GCN with DropMessage, DropRate from MLP
weight_decay = 0e-4
drop_rate = 0.0

[models.tgat]
# TGAT
weight_decay = 0e-4