# Basic configs
model = "gcn"
dataset = "Yelp"
device = "cuda:0"

hidden_size = 64
num_layers = 2
dropout = 0.0
random_seed = 0

# Learning rate
lr = 0.01

# Drop Message rate
drop_rate = 0.25

metrics = ["AUC", "AP"]

use_early_stopping = true
early_stopping_patience = 10

log_path = "./logs.txt"

# Dataset configs

[datasets.DGraph]
num_classes = 2
loss_weight = 50

[datasets.Cora]
num_classes = 7
loss_weight = 1

[datasets.Wikipedia]
num_classes = 2
loss_weight = 50

[datasets.Yelp]
num_classes = 2
loss_weight = 50

# Model configs

[models.gcn]
# GCN
weight_decay = 5e-7

[models.sage]
# GraphSAGE
weight_decay = 5e-7

[models.dropgcn]
# GCN with DropMessage
weight_decay = 0e-4

[models.mlpdropgcn]
# GCN with DropMessage, DropRate from MLP
weight_decay = 0e-4

[models.tgat]
# TGAT
weight_decay = 0e-4

[models.h2gcn]
# H2GCN
weight_decay = 0e-4

[models.mlp]
# MLP
weight_decay = 0e-4

[models.amnet]
# AMNet
weight_decay = 0e-4
