# Basic configs
model = "tgat"
device = "cuda:0"
num_classes = 2
hidden_size = 64
num_layers = 2
dropout = 0.0

lr = 0.01 # Learning rate
metrics = ["AUC", "AP"]

log_path = "./logs.txt"

[models.gcn]
# GCN
weight_decay = 5e-7

[models.tgat]
# TGAT
weight_decay = 0e-4